name = "ofmszr"
print(len(name))
print(name.find("o"))
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.isdigit())
print(name.isalpha())
print(name.count("f"))
print(name.count("o"))
print(name.replace("o" , "ö"))
print(name*4)